name: CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Cache Gradle
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-${{ runner.os }}-

    - name: create secret file
      run : |
          echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}\\n" >> secrets.properties
          echo "KEY_STORE_ALIAS=${{ secrets.KEY_STORE_ALIAS }}\\n" >> secrets.properties
          echo "KEY_STORE_PASSWORD=${{ secrets.KEY_STORE_PASSWORD }}\\n" >> secrets.properties
          echo "PEXELS_API_KEY=${{ secrets.PEXELS_API_KEY }}\\n" >> secrets.properties
          echo "PEXELS_BASE_URL=${{ secrets.PEXELS_BASE_URL }}\\n" >> secrets.properties
          echo "SIGNING_KEY_ALIAS=${{ secrets.SIGNING_KEY_ALIAS }}\\n" >> secrets.properties
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run tests
        run: ./gradlew assembleDebug

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps: 
      - name: Create jks file
        run : echo {{ secrets.KEYSTORE_JKS_FILE_CONTENT }} | base64 -d >> app/woli_keystore.jks
      - name: create secret file
        run : |
          echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}\\n" >> secrets.properties
          echo "KEY_STORE_ALIAS=${{ secrets.KEY_STORE_ALIAS }}\\n" >> secrets.properties
          echo "KEY_STORE_PASSWORD=${{ secrets.KEY_STORE_PASSWORD }}\\n" >> secrets.properties
          echo "PEXELS_API_KEY=${{ secrets.PEXELS_API_KEY }}\\n" >> secrets.properties
          echo "PEXELS_BASE_URL=${{ secrets.PEXELS_BASE_URL }}\\n" >> secrets.properties
          echo "SIGNING_KEY_ALIAS=${{ secrets.SIGNING_KEY_ALIAS }}\\n" >> secrets.properties

      - name: Build Release AAB
        run: ./gradlew app:bundleRelease

      - name: Add service account json
        run: |
          echo "${{ secrets.SERVICE_ACCOUNT_JSON }}" >> secrets_account.text
          echo "SERVICE_ACCOUNT_JSON_TEXT=${{ cat < secrets_account.json }}\\n" >> $GITHUB_ENV      

      - name: Deploy to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ SERVICE_ACCOUNT_JSON_TEXT }}
          packageName: com.wiseowl.woli
          releaseFiles: app/build/outputs/bundle/release/*.aab
          track: internal
